### ISSUE TITLE
Скласти інтро.

### ISSUE THREAD

**Issue by luamoris** [luamoris/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by luamoris-land** [comment]
#### 1. Чем я занимаюсь, и что я делаю?
> Программист. Углубленно изучаю технологии, которые связаны с инженерией программного обеспечения. Большую часть времени посвящаю WEB направлению, в частности front-end и back-end разработки.

#### 2. Что мне нравиться делать?
> Мне нравиться совершенствовать и создавать уникальные продукты; изучать новые технологии и внедрять их в свои проекты; делиться своим опытом с другими.

#### 3. Что хочется делать лучше?
> Хочу научиться лучше писать доступные руководства по изученным технологиям; создавать хорошие библиотеки с использованием тестирования; глубже разбираться в изучаемых технологиях; придерживаться приоритетов.

#### 4. Что важно делать?
> Чтобы достичь всех поставленных целей важно изучить английский язык; уделять больше времени на практику; тренировать любопытство и креативность; поддерживать дисциплину, терпение и сосредоточенность.
