### ISSUE TITLE
Скласти блок контактної інформації.

### ISSUE THREAD

**Issue by luamoris** [luamoris/homepage#6]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by luamoris-land** [comment]
|NETWORK|LINK|
|:-:|:--|
|Linkedin|https://www.linkedin.com/in/iosif-isachko-2631061a7|
|Telegram|https://t.me/I0S1F|
|Behance|https://www.behance.net/yaiosifua2980|
|GitHub|https://github.com/luamoris|
|GitLab|https://gitlab.com/luamoris|
|BitBucket|https://bitbucket.org/iosif_isachko|
|Codepen|https://codepen.io/luamoris/pens/public|
