### ISSUE TITLE
Скласти таймлайн.

### ISSUE THREAD

**Issue by luamoris** [luamoris/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by luamoris-land** [comment]
2002
1. Год оказался трудным. В этот год народился Я.

#### 2019
1. Поступил в "Киевский Политехнический Институт им. И. Сикорского" на специальность "Инженерия программного обеспечения".
2. Был одним из организаторов конкурса "Mister FAM 2019".
Отвечал за такие направления как: дизайн, фандрайзинг, музыка (диджей).

#### 2020
1. Был одним из организаторов  "Misis FAM 2020"
Отвечал за такие направления как: дизайн, фандрайзинг, музыка (диджей).

#### 2021
1. Вступил в студенческую организацию ESTIEM, в роли PR дизайнера.
2. Принял участие в челлендже Fakefighters.
3. Прошел первый этап отбора в Academy 2021.
