### ISSUE TITLE
Скласти додаткові інформаційні блоки.

### ISSUE THREAD

**Issue by luamoris** [luamoris/homepage#8]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by luamoris-land** [comment]
#### 1. Языки
1. Русский
2. Украинский

#### 2. Навыки и Хобби? 

Навыки: не определенно.
Хобби: настольный теннис, книги.

#### 3. Последние проекты на GitHub

##### API: 
https://api.github.com/users/luamoris/repos?accept=application/vnd.github.v3+json&sort=pushed&direction=desc&per_page=5

##### Обязательные поля объекта:
|FIELD|
|:-:|
|id|
|name|
|html_url|
|description|
|created_at|
|updated_at|
|language|
